# docker-compose.yml
services:
  opa:
    image: openpolicyagent/opa:latest
    command: ["run","--server","--watch","/policies","--addr=0.0.0.0:8181","--log-level=debug"]
    volumes: ["./policies:/policies:ro"]
    healthcheck:
      test: ["CMD", "/opa", "version"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    environment:
      # These settings are fine.
      OPA_URL: "http://opa:8181/v1/data/gateway/deny"
      OPA_FAIL_CLOSED: "true"
      JWT_SECRET: "dev-secret"
    ports: ["8000:8000"]
    depends_on:
      opa:
        condition: service_healthy
